// Copyright 2015 The Vanadium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// This file was auto-generated by the vanadium vdl tool.
// Package: v.io/v23/uniqueid

#include <string.h>

#include "miniv.h"
#include "v23_uniqueid.h"


static err_t v23_uniqueid_Id_decode(buf_t *in, void *out) {
  if (in->len < 16) {
    err_t err = ERR_DECVOM; ck();
  }
  memcpy(out, in->buf, 16);
  return ERR_OK;

}



void v23_uniqueid_register() {

    vomRegister(bufFromString("v.io/v23/uniqueid.Id"),
                kindArray,
                sizeof(v23_uniqueid_Id),
                v23_uniqueid_Id_decode);

}
